### ISSUE TITLE
Support for SHA-256 algorithm

### ISSUE THREAD

**Issue by mayuran19** [lestrrat-go/xmlsec#2]
Does this support the SHA-256 algorithm? I cannot see the option for SHA-256

**Comment by lestrrat** [comment]
Please define "this": this library contains JWS, JWE, JWT, JWK, etc and they don't all share the same algorithms b/c they are for different things.

Also, If I'm not mistaken, there isn't a "SHA-256" algorithm defined in any of the above. There is for example, A128CBC_HS256, which is for JWE. But I don't think a plain SHA-256 is defined in any of the specs.

**Comment by lestrrat** [comment]
Oh yikes, I thought this was for a different repo. My bad...

**Comment by lestrrat** [comment]
Re-reading xmlsec now.

**Comment by lestrrat** [comment]
This library is a wrapper around xmlsec library, so as long as xmlsec supports it, it should work.

Googling for `xmlsec sha256` resulted in this post https://www.aleksey.com/pipermail/xmlsec/2005/007038.html

HTH
